
paths:
  output_dir: "C:/CTI/results"
  datasets_dir: "C:/CTI/datasets"
dataset:
  name: "dnrti"
  file: "C:/CTI/datasets/DNRTI/dnrti_aug_stix2_je.json"
models:
  extraction_model: "gemma2:9b"
  embedding_model: "nomic-embed-text"
