#!/usr/bin/env python3
"""
McNemar's Test for Statistical Significance
=============================================
Compares paired binary outcomes (correct/incorrect) between two systems
on the same test queries.

Comparisons:
  1. Fine-tuned reranker vs GPT-5.4-mini (zero-shot)
  2. Fine-tuned reranker vs GPT-5.4-mini (few-shot)
  3. Fine-tuned reranker vs BM25-only baseline

McNemar's test examines whether the disagreements between two classifiers
are symmetric. It uses only the discordant pairs (queries where one system
is right and the other is wrong).

Usage:
  python mcnemar_test.py

  Expects these files to exist (generated by prior scripts):
    eval_results/explanations.json                          (reranker results)
    llm_baseline_results/responses_gpt-5.4-mini_zero_shot.jsonl  (LLM zero-shot)
    llm_baseline_results/responses_gpt-5.4-mini_few_shot.jsonl   (LLM few-shot)
    data/reranker_pairs_enriched.jsonl                      (for BM25 baseline)

Author: Shane Waldrop — Angelo State University / ARL Grant W911NF-24-2-0180
"""

import json
import re
import sys
import random
import numpy as np
from collections import defaultdict
from pathlib import Path

RANDOM_SEED = 42
ATTACK_ID_RE = re.compile(r'(TA\d{4}|T\d{4}(?:\.\d{3})?|S\d{4})')


# ── Load reranker results from explanations.json ─────────────────────────────

def load_reranker_results(path="eval_results/explanations.json"):
    """Load per-query correct/incorrect from the explainability module output."""
    if not Path(path).exists():
        sys.exit(f"[FAIL] Reranker results not found: {path}")

    with open(path, 'r', encoding='utf-8') as f:
        explanations = json.load(f)

    results = {}
    for expl in explanations:
        # Use query text as key since that's what both systems share
        query = expl['query']
        correct = expl['prediction']['correct']
        results[query] = 1 if correct else 0

    print(f"  Loaded {len(results)} reranker results from {path}")
    n_correct = sum(results.values())
    print(f"    Correct: {n_correct}/{len(results)} "
          f"({n_correct/len(results):.1%})")
    return results


# ── Load LLM results from response JSONL ─────────────────────────────────────

def load_llm_results(path):
    """Load per-query correct/incorrect from LLM baseline responses."""
    if not Path(path).exists():
        return None

    responses = []
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            if line.strip():
                responses.append(json.loads(line))

    results = {}
    for resp in responses:
        if resp.get('error'):
            continue
        query = resp['query_raw']
        predicted_id = None
        match = ATTACK_ID_RE.search(resp.get('llm_response', ''))
        if match:
            predicted_id = match.group(1)
        gold_ids = resp['gold_ids']
        correct = predicted_id in gold_ids if predicted_id else False
        results[query] = 1 if correct else 0

    print(f"  Loaded {len(results)} LLM results from {path}")
    n_correct = sum(results.values())
    print(f"    Correct: {n_correct}/{len(results)} "
          f"({n_correct/len(results):.1%})")
    return results


# ── Load BM25-only results from enriched JSONL ──────────────────────────────

def load_bm25_results(data_path="data/reranker_pairs_enriched.jsonl"):
    """Compute BM25-only P@1 by taking the first candidate per query
    (BM25 rank-1) and checking if it's a gold label.
    Only for the test split queries."""
    if not Path(data_path).exists():
        return None

    # First, load and group data (same as other scripts)
    query_data = defaultdict(lambda: {
        'query_raw': None, 'actor': None, 'candidates': [],
        'positive_count': 0, 'negative_count': 0,
    })
    with open(data_path, 'r', encoding='utf-8') as f:
        for line in f:
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            qn = row.get('query_norm', '')
            qr = row.get('query_raw', '')
            if not qn or not qr:
                continue
            if query_data[qn]['query_raw'] is None:
                query_data[qn]['query_raw'] = qr
                query_data[qn]['actor'] = row.get('actor', 'unknown')
            query_data[qn]['candidates'].append({
                'label': row.get('label', 0),
            })
            if row.get('label', 0) == 1:
                query_data[qn]['positive_count'] += 1

    # Recreate test split
    random.seed(RANDOM_SEED)
    queries_by_actor = defaultdict(list)
    for qn, data in query_data.items():
        if data['actor'].startswith('external_'):
            continue
        if data['positive_count'] > 0:
            queries_by_actor[data['actor']].append(qn)

    test_queries = []
    for actor, queries in queries_by_actor.items():
        random.shuffle(queries)
        n = len(queries)
        n_train = int(n * 0.8)
        n_val = int(n * 0.1)
        test_queries.extend(queries[n_train + n_val:])
    random.shuffle(test_queries)

    # BM25 rank-1 = first candidate in the list (BM25 retrieval order)
    results = {}
    for qn in test_queries:
        if qn not in query_data:
            continue
        data = query_data[qn]
        if not data['candidates'] or data['positive_count'] == 0:
            continue
        # First candidate is BM25 rank-1
        bm25_top1_correct = data['candidates'][0]['label'] == 1
        results[data['query_raw']] = 1 if bm25_top1_correct else 0

    print(f"  Computed {len(results)} BM25-only results")
    n_correct = sum(results.values())
    print(f"    Correct: {n_correct}/{len(results)} "
          f"({n_correct/len(results):.1%})")
    return results


# ── McNemar's Test ───────────────────────────────────────────────────────────

def mcnemar_test(results_a, results_b, name_a, name_b):
    """
    Run McNemar's test on paired binary results.

    Builds a 2x2 contingency table:
                        System B correct    System B wrong
    System A correct        n11                 n10
    System A wrong          n01                 n00

    McNemar's statistic uses only discordant pairs (n10, n01):
      chi2 = (|n10 - n01| - 1)^2 / (n10 + n01)   [with continuity correction]

    Null hypothesis: the two systems have the same error rate.
    """
    # Find shared queries
    shared = set(results_a.keys()) & set(results_b.keys())
    if len(shared) == 0:
        print(f"\n  [SKIP] No shared queries between {name_a} and {name_b}")
        return None

    # Build contingency table
    n11 = 0  # both correct
    n10 = 0  # A correct, B wrong
    n01 = 0  # A wrong, B correct
    n00 = 0  # both wrong

    for query in shared:
        a = results_a[query]
        b = results_b[query]
        if a == 1 and b == 1:
            n11 += 1
        elif a == 1 and b == 0:
            n10 += 1
        elif a == 0 and b == 1:
            n01 += 1
        else:
            n00 += 1

    total = n11 + n10 + n01 + n00
    discordant = n10 + n01

    print(f"\n  {'='*60}")
    print(f"  McNEMAR'S TEST: {name_a} vs {name_b}")
    print(f"  {'='*60}")

    print(f"\n  Contingency Table ({total} shared queries):")
    print(f"  {'':>25} | {name_b+' correct':>15} | {name_b+' wrong':>15}")
    print(f"  {'-'*25}-+-{'-'*15}-+-{'-'*15}")
    print(f"  {name_a+' correct':>25} | {n11:>15} | {n10:>15}")
    print(f"  {name_a+' wrong':>25} | {n01:>15} | {n00:>15}")

    print(f"\n  Concordant pairs (both agree): {n11 + n00}")
    print(f"  Discordant pairs (disagree):   {discordant}")
    print(f"    {name_a} right, {name_b} wrong: {n10}")
    print(f"    {name_a} wrong, {name_b} right: {n01}")

    if discordant == 0:
        print(f"\n  No discordant pairs — systems agree on every query.")
        print(f"  McNemar's test is not applicable.")
        return None

    # McNemar's chi-squared with continuity correction
    chi2 = (abs(n10 - n01) - 1) ** 2 / (n10 + n01)

    # McNemar's chi-squared without continuity correction
    chi2_no_cc = (n10 - n01) ** 2 / (n10 + n01)

    # p-value from chi-squared distribution with 1 degree of freedom
    # Using scipy if available, otherwise manual approximation
    try:
        from scipy.stats import chi2 as chi2_dist
        p_value = 1 - chi2_dist.cdf(chi2, df=1)
        p_value_no_cc = 1 - chi2_dist.cdf(chi2_no_cc, df=1)
        used_scipy = True
    except ImportError:
        # Manual approximation using the complementary error function
        import math
        def chi2_pvalue_approx(x):
            """Approximate p-value for chi2 with df=1."""
            return math.erfc(math.sqrt(x / 2))
        p_value = chi2_pvalue_approx(chi2)
        p_value_no_cc = chi2_pvalue_approx(chi2_no_cc)
        used_scipy = False

    print(f"\n  McNemar's chi-squared (with continuity correction): {chi2:.4f}")
    print(f"  McNemar's chi-squared (without correction):         {chi2_no_cc:.4f}")
    print(f"  p-value (with correction):    {p_value:.6f}")
    print(f"  p-value (without correction): {p_value_no_cc:.6f}")
    if not used_scipy:
        print(f"  (Note: scipy not available, using erfc approximation)")

    # Significance assessment
    if p_value < 0.001:
        sig = "*** HIGHLY SIGNIFICANT (p < 0.001)"
    elif p_value < 0.01:
        sig = "**  SIGNIFICANT (p < 0.01)"
    elif p_value < 0.05:
        sig = "*   SIGNIFICANT (p < 0.05)"
    else:
        sig = "    NOT SIGNIFICANT (p >= 0.05)"

    print(f"\n  Significance: {sig}")

    # Direction of advantage
    if n10 > n01:
        print(f"  Direction: {name_a} is significantly better")
    elif n01 > n10:
        print(f"  Direction: {name_b} is significantly better")
    else:
        print(f"  Direction: No advantage (equal discordant counts)")

    # Paper-ready sentence
    print(f"\n  FOR THE PAPER:")
    if p_value < 0.05:
        winner = name_a if n10 > n01 else name_b
        loser = name_b if n10 > n01 else name_a
        print(f'  "The difference between {winner} and {loser} is')
        print(f'   statistically significant (McNemar\'s test,')
        print(f'   chi2 = {chi2_no_cc:.2f}, p < {format_p(p_value_no_cc)})."')
    else:
        print(f'  "The difference between {name_a} and {name_b} is')
        print(f'   not statistically significant (McNemar\'s test,')
        print(f'   chi2 = {chi2_no_cc:.2f}, p = {p_value_no_cc:.3f})."')

    return {
        'comparison': f'{name_a} vs {name_b}',
        'n_shared': total,
        'n11': n11, 'n10': n10, 'n01': n01, 'n00': n00,
        'chi2': round(chi2, 4),
        'chi2_no_cc': round(chi2_no_cc, 4),
        'p_value': p_value,
        'p_value_no_cc': p_value_no_cc,
        'significant': p_value < 0.05,
        'advantage': name_a if n10 > n01 else name_b,
    }


def format_p(p):
    """Format p-value for paper citation."""
    if p < 0.001:
        return "0.001"
    elif p < 0.01:
        return "0.01"
    elif p < 0.05:
        return "0.05"
    else:
        return f"{p:.3f}"


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    print("\n" + "=" * 60)
    print("  STATISTICAL SIGNIFICANCE TESTS")
    print("  McNemar's Test for Paired Binary Outcomes")
    print("=" * 60)

    # Load all available results
    print("\n  Loading results...")
    reranker = load_reranker_results("eval_results/explanations.json")

    llm_zs = load_llm_results(
        "llm_baseline_results/responses_gpt-5.4-mini_zero_shot.jsonl")
    llm_fs = load_llm_results(
        "llm_baseline_results/responses_gpt-5.4-mini_few_shot.jsonl")
    bm25 = load_bm25_results("data/reranker_pairs_enriched.jsonl")

    # Run all available comparisons
    all_results = []

    # Comparison 1: Reranker vs LLM zero-shot
    if llm_zs:
        result = mcnemar_test(reranker, llm_zs,
                              "Reranker (91.1%)", "GPT-5.4-mini ZS")
        if result:
            all_results.append(result)

    # Comparison 2: Reranker vs LLM few-shot
    if llm_fs:
        result = mcnemar_test(reranker, llm_fs,
                              "Reranker (91.1%)", "GPT-5.4-mini FS")
        if result:
            all_results.append(result)

    # Comparison 3: Reranker vs BM25-only
    if bm25:
        result = mcnemar_test(reranker, bm25,
                              "Reranker (91.1%)", "BM25-only")
        if result:
            all_results.append(result)

    # Comparison 4: BM25 vs LLM (interesting: does keyword matching beat the LLM?)
    if bm25 and llm_zs:
        result = mcnemar_test(bm25, llm_zs,
                              "BM25-only", "GPT-5.4-mini ZS")
        if result:
            all_results.append(result)

    # Summary
    if all_results:
        print(f"\n  {'='*60}")
        print(f"  SUMMARY OF ALL COMPARISONS")
        print(f"  {'='*60}")
        print(f"\n  {'Comparison':<40} | {'chi2':>8} | {'p-value':>10} | {'Sig?':>5}")
        print(f"  {'-'*40}-+-{'-'*8}-+-{'-'*10}-+-{'-'*5}")
        for r in all_results:
            sig_mark = "***" if r['p_value'] < 0.001 else \
                       "**" if r['p_value'] < 0.01 else \
                       "*" if r['p_value'] < 0.05 else "ns"
            print(f"  {r['comparison']:<40} | {r['chi2_no_cc']:>8.2f} | "
                  f"{r['p_value_no_cc']:>10.6f} | {sig_mark:>5}")

        # Save results
        out_path = Path("llm_baseline_results/mcnemar_results.json")
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, 'w', encoding='utf-8') as f:
            json.dump(all_results, f, indent=2, default=str)
        print(f"\n  Results saved to: {out_path}")

    print(f"\n  [DONE] Statistical significance tests complete.")


if __name__ == '__main__':
    main()
